_target_: src.nn.models.diffusion_transformer_policy.DiffusionTransformerPolicyModule
_recursive_: false

shape_meta: ${model_tuning.shape_meta}
# diffusion
beta_end: ${model_tuning.beta_end}
beta_schedule: ${model_tuning.beta_schedule}
beta_start: ${model_tuning.beta_start}
clip_sample: ${model_tuning.clip_sample}
num_train_timesteps: ${model_tuning.num_train_timesteps}
prediction_type: ${model_tuning.prediction_type}
variance_type: ${model_tuning.variance_type}
num_inference_steps: ${model_tuning.num_inference_steps}
# action
horizon: ${model_tuning.horizon}
n_action_steps: ${model_tuning.n_action_steps}
n_obs_steps: ${model_tuning.n_obs_steps}
# transformer
n_layer: ${model_tuning.n_layer}
n_head: ${model_tuning.n_head}
n_emb: ${model_tuning.n_emb}
p_drop_emb: ${model_tuning.p_drop_emb}
p_drop_attn: ${model_tuning.p_drop_attn}
causal_attn: ${model_tuning.causal_attn}
n_cond_layers: ${model_tuning.n_cond_layers}
# training
learning_rate: ${model_tuning.learning_rate}
weight_decay: ${model_tuning.weight_decay}
warmup_steps: ${model_tuning.warmup_steps}
lr_min_ratio: ${model_tuning.lr_min_ratio}
rollout_during_val: ${model_tuning.rollout_during_val}
